import { ImobileProduct } from "../models/mobile.interface";


export let products:Array<ImobileProduct> =[
    {
      brand: "Samsung",
      image:"https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s21-fe-5g.jpg",
      model: "Galaxy S21",
      color: "Phantom Black",
      rating:4.2,
      storage: "128GB",
      price: "₹74,000",
      screen_size: "6.2 inches",
      isAvailable:true,
      processor: "Exynos 2100",
      camera_setup: "Triple rear (12MP+12MP+64MP), 10MP front",
      battery_capacity: "4000mAh",
      features: ["5G connectivity", "120Hz refresh rate display", "Wireless charging"]
    },
    {
      brand: "Apple",
      image:"",
      model: "Iphone 13",
      color: "Phantom Black",
      rating:4.2,
      storage: "128GB",
      price: "₹74,000",
      screen_size: "6.2 inches",
      isAvailable:true,
      processor: "Exynos 2100",
      camera_setup: "Triple rear (12MP+12MP+64MP), 10MP front",
      battery_capacity: "4000mAh",
      features: ["5G connectivity", "120Hz refresh rate display", "Wireless charging"]
    },
    {
      brand: "Apple",
      image:"https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-13-pro.jpg",
      model: "iPhone 13 Pro",
      color: "Graphite",
      storage: "256GB",
      rating:4.8,
      price: "₹1,03,900",
      screen_size: "6.1 inches",
      processor: "A15 Bionic",
      isAvailable:true,
      camera_setup: "Triple rear (12MP+12MP+12MP), 12MP front",
      battery_capacity: "3095mAh",
      features: ["Face ID", "Ceramic Shield front cover", "MagSafe technology"]
    },
    {
      brand: "OnePlus",
      model: "9 Pro",
      image:"https://fdn2.gsmarena.com/vv/bigpic/oneplus-9-pro-.jpg",
      color: "Morning Mist",
      storage: "256GB",
      price: "₹80,000",
      rating:3.4,
      screen_size: "6.7 inches",
      isAvailable:true,
      processor: "Snapdragon 888",
      camera_setup: "Quad rear (48MP+50MP+8MP+2MP), 16MP front",
      battery_capacity: "4500mAh",
      features: ["Fluid AMOLED display", "Warp Charge 65T", "Dual stereo speakers"]
    },
    {
      brand: "OnePlus",
      model: "9 Pro",
      image:"",
      color: "Morning Mist",
      storage: "256GB",
      price: "₹80,000",
      rating:3.4,
      screen_size: "6.7 inches",
      isAvailable:true,
      processor: "Snapdragon 888",
      camera_setup: "Quad rear (48MP+50MP+8MP+2MP), 16MP front",
      battery_capacity: "4500mAh",
      features: ["Fluid AMOLED display", "Warp Charge 65T", "Dual stereo speakers"]
    },
    {
      brand: "Google",
      image:"https://fdn2.gsmarena.com/vv/bigpic/google-pixel-6.jpg",
      model: "Pixel 6",
      color: "Sorta Sunny",
      storage: "128GB",
      price: "₹58,500",
      rating:3.5,
      screen_size: "6.4 inches",
      processor: "Google Tensor",
      isAvailable:false,
      camera_setup: "Dual rear (50MP+12MP), 8MP front",
      battery_capacity: "4614mAh",
      features: ["Google Assistant", "Tensor Processing Unit", "Night Sight photography"]
    },
    {
      brand: "Xiaomi",
      image:"https://fdn2.gsmarena.com/vv/bigpic/xiaomi-mi11.jpg",
      model: "Mi 11",
      color: "Midnight Gray",
      storage: "256GB",
      price: "₹55,000",
      rating:3.9,
      screen_size: "6.81 inches",
      processor: "Snapdragon 888",
      isAvailable:true,
      camera_setup: "Triple rear (108MP+13MP+5MP), 20MP front",
      battery_capacity: "4600mAh",
      features: ["120Hz refresh rate display", "Fast charging", "In-screen fingerprint sensor"]
    },
    {
      brand: "Huawei",
      image:"https://fdn2.gsmarena.com/vv/bigpic/huawei-p40-pro.jpg",
      model: "P40 Pro",
      color: "Silver Frost",
      storage: "256GB",
      price: "₹64,900",
      isAvailable:false,
      screen_size: "6.58 inches",
      rating:3.4,
      processor: "Kirin 990 5G",
      camera_setup: "Quad rear (50MP+12MP+40MP+TOF 3D), 32MP front",
      battery_capacity: "4200mAh",
      features: ["Leica Quad Camera System", "Dual-View Video", "Water and dust resistant"]
    },
    {
      brand: "Huawei",
      image:"",
      model: "P40 Pro",
      color: "Silver Frost",
      storage: "256GB",
      price: "₹64,900",
      isAvailable:false,
      screen_size: "6.58 inches",
      rating:3.4,
      processor: "Kirin 990 5G",
      camera_setup: "Quad rear (50MP+12MP+40MP+TOF 3D), 32MP front",
      battery_capacity: "4200mAh",
      features: ["Leica Quad Camera System", "Dual-View Video", "Water and dust resistant"]
    },
    {
      brand: "Sony",
      image:"https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-1-iii.jpg",
      model: "Xperia 1 III",
      color: "Frosted Black",
      storage: "256GB",
      price: "₹92,900",
      screen_size: "6.5 inches",
      rating:3.8,
      processor: "Snapdragon 888",
      isAvailable:false,
      camera_setup: "Triple rear (12MP+12MP+12MP), 8MP front",
      battery_capacity: "4500mAh",
      features: ["4K OLED HDR display", "Cinematic recording", "3D audio"]
    },
    {
      brand: "Motorola",
      image:"https://fdn2.gsmarena.com/vv/bigpic/motorola-edge-plus-2023.jpg",
      model: "Edge+",
      color: "Thunder Grey",
      storage: "256GB",
      price: "₹74,000",
      screen_size: "6.7 inches",
      processor: "Snapdragon 865",
      rating:3.2,
      isAvailable:true,
      camera_setup: "Triple rear (108MP+16MP+8MP), 25MP front",
      battery_capacity: "5000mAh",
      features: ["5G connectivity", "Edge display", "Ready For platform"]
    },
    {
      brand: "LG",
      image:"https://fdn2.gsmarena.com/vv/bigpic/lg-wing.jpg",
      model: "Wing 5G",
      color: "Aurora Gray",
      storage: "256GB",
      price: "₹74,000",
      rating:2.7,
      isAvailable:false,
      screen_size: "6.8 inches",
      processor: "Snapdragon 765G",
      camera_setup: "Triple rear (64MP+13MP+12MP), 32MP pop-up front",
      battery_capacity: "4000mAh",
      features: ["Swivel display", "Gimbal Motion Camera", "LG 3D Sound Engine"]
    },
    {
      brand: "LG",
      image:"",
      model: "Wing 5G",
      color: "Aurora Gray",
      storage: "256GB",
      price: "₹74,000",
      rating:2.7,
      isAvailable:false,
      screen_size: "6.8 inches",
      processor: "Snapdragon 765G",
      camera_setup: "Triple rear (64MP+13MP+12MP), 32MP pop-up front",
      battery_capacity: "4000mAh",
      features: ["Swivel display", "Gimbal Motion Camera", "LG 3D Sound Engine"]
    },
    {
      brand: "Realme",
      image:"https://fdn2.gsmarena.com/vv/bigpic/realme-gt-neo2.jpg",
      model: "GT Neo 2",
      color: "Neo Green",
      storage: "128GB",
      price: "₹28,000",
      isAvailable:true,
      rating:2.4,
      screen_size: "6.62 inches",
      processor: "Snapdragon 870",
      camera_setup: "Triple rear (64MP+8MP+2MP), 16MP front",
      battery_capacity: "5000mAh",
      features: ["120Hz Super AMOLED display", "Dual stereo speakers", "Dolby Atmos"]
    }
  ];